### ISSUE TITLE
Elixir 0.10

### ISSUE THREAD

**Issue by jbrooksuk** [rynocouse/laravel-elixir-compass#13]
Can we get support for Elixir 0.10 please? There is an error of:

```
Error: Cannot find module 'laravel-elixir/ingredients/helpers/utilities'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/james.brooks/Sites/chainwhale/node_modules/laravel-elixir-compass/index.js:4:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by JoeCianflone** [comment]
@jbrooksuk I resolved this in a new repo so it could be pushed to NPM.  

You can find the repo here: https://github.com/JoeCianflone/laravel-elixir-sass-compass
the npm link here: https://www.npmjs.com/package/laravel-elixir-sass-compass
to install it should just be npm install laravel-elixir-sass-compass
